package MainP;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class FMain extends javax.swing.JFrame
{
    private final int ButtonSize = 50, spacingS = 5, spacingL = 10;
    private final ArrayList<ColorButton> ButtReff = new ArrayList();

    protected static GridPanel G;

    /** Creates new form FMain */
    public FMain()
      {
        initComponents();
      }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        titL = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FloodMe!");
        setBackground(new java.awt.Color(102, 255, 102));
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        setForeground(java.awt.Color.red);
        setName("FrMain"); // NOI18N
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        titL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titL.setText("jLabel1");
        titL.setName(""); // NOI18N

        jMenu1.setText("App");

        jMenuItem1.setText("About");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Game");

        jMenu3.setText("New game");

        jMenuItem10.setText("Pointless");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem3.setText("Easy");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Medium");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Difficult");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem9.setText("Haha u funny");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenu2.add(jMenu3);

        jMenu4.setText("Color pack");

        jMenuItem6.setText("Basic");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Six shades of gray");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Jajou");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titL)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titL)
                .addGap(0, 250, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        System.out.println("Showing info message box");
        JOptionPane.showMessageDialog(null, "FloodMe!, by BogdanBBA\n\nv1.0 beta - February 14th-15th, 2014", "App info", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed
        System.out.println("Exiting, goodbye!");
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        try
          {
            ImageIcon icon = new ImageIcon(new java.io.File(".").getCanonicalPath() + "\\icon.png");
            this.setIconImage(icon.getImage());
          }
        catch (IOException ex)
          {
            Logger.getLogger(FMain.class.getName()).log(Level.SEVERE, null, ex);
          }
        //
        titL.setLocation(spacingL, spacingL);
        for (int i = 0; i < GridPanel.Colors.length; i++)
          {
            ColorButton CB = new ColorButton(GridPanel.Colors[i], GridPanel.TextColors[i], GridPanel.ColorNames[i],
                                             spacingL, titL.getHeight() + spacingL + i * (spacingS + ButtonSize), ButtonSize, ButtonSize);
            CB.setName(String.format("b%d", i));
            CB.addMouseListener(new ColorButton_MouseListener());
            ButtReff.add(CB);
            this.add(CB);
          }
        G = new GridPanel(GridPanel.GridSizeM, 2 * spacingL + ButtonSize, titL.getHeight() + spacingL,
                          ButtonSize * GridPanel.Colors.length + (GridPanel.Colors.length - 1) * spacingS,
                          ButtonSize * GridPanel.Colors.length + (GridPanel.Colors.length - 1) * spacingS);
        this.add(G);
        //
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension window = new Dimension(G.getWidth() + 3 * spacingL + ButtonSize + 4,
                                         52 + titL.getHeight() + GridPanel.Colors.length * ButtonSize + 20 + (GridPanel.Colors.length - 1) * 5);
        this.setBounds(screen.width / 2 - window.width / 2, screen.height / 2 - window.height / 2, window.width, window.height);
        this.jMenuItem4ActionPerformed(null);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem3ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem3ActionPerformed
        System.out.println("Starting a new game");
        G.Moves = 0;
        G.MaxMoves = (int) Math.round(2 * GridPanel.GridSizeS);
        titL.setText(String.format("Moves: %d / %d", G.Moves, G.MaxMoves));
        G.GenerateRandomly(GridPanel.GridSizeS);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem4ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem4ActionPerformed
        System.out.println("Starting a new game");
        G.Moves = 0;
        G.MaxMoves = (int) Math.round(1.5 * GridPanel.GridSizeM);
        titL.setText(String.format("Moves: %d / %d", G.Moves, G.MaxMoves));
        G.GenerateRandomly(GridPanel.GridSizeM);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem5ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem5ActionPerformed
        System.out.println("Starting a new game");
        G.Moves = 0;
        G.MaxMoves = (int) Math.round(1.25 * GridPanel.GridSizeL);
        titL.setText(String.format("Moves: %d / %d", G.Moves, G.MaxMoves));
        G.GenerateRandomly(GridPanel.GridSizeL);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem6ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem6ActionPerformed
        System.out.println("Changing color pack");
        G.ChangeColorPack(new Color[]
          {
            Color.BLACK, Color.GRAY, Color.BLUE, Color.GREEN, Color.RED, Color.WHITE
          },
                          new Color[]
                            {
                              Color.WHITE, Color.WHITE, Color.WHITE, Color.BLACK, Color.WHITE, Color.BLACK
                            },
                          new String[]
                            {
                              "Black", "Gray", "Blue", "Green", "Red", "White"
                            });
        G.repaint();
        for (int i = 0; i < GridPanel.Colors.length; i++)
            ButtReff.get(i).setColorsAndCaption(GridPanel.Colors[i], GridPanel.TextColors[i], GridPanel.ColorNames[i]);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem7ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem7ActionPerformed
        System.out.println("Changing color pack");
        G.ChangeColorPack(new Color[]
          {
            Color.BLACK, new Color(51, 51, 51), new Color(102, 102, 102), new Color(153, 153, 153), new Color(204, 204, 204), Color.WHITE
          },
                          new Color[]
                            {
                              Color.WHITE, Color.WHITE, Color.WHITE, Color.BLACK, Color.BLACK, Color.BLACK
                            },
                          new String[]
                            {
                              "Black", "Gray 80%", "Gray 60%", "Gray 40%", "Gray 20%", "White"
                            });
        G.repaint();
        for (int i = 0; i < GridPanel.Colors.length; i++)
            ButtReff.get(i).setColorsAndCaption(GridPanel.Colors[i], GridPanel.TextColors[i], GridPanel.ColorNames[i]);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem8ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem8ActionPerformed
        System.out.println("Changing color pack");
        G.ChangeColorPack(new Color[]
          {
            new Color(25, 62, 102), new Color(126, 17, 13), new Color(103, 156, 63), new Color(170, 61, 165), new Color(176, 255, 0), new Color(255, 242, 111)
          },
                          new Color[]
                            {
                              Color.WHITE, Color.WHITE, Color.WHITE, Color.WHITE, Color.BLACK, Color.BLACK
                            },
                          new String[]
                            {
                              "Blau", "Rouzhe", "Ver", "Violois", "Vergrain", "Yallou"
                            });
        G.repaint();
        for (int i = 0; i < GridPanel.Colors.length; i++)
            ButtReff.get(i).setColorsAndCaption(GridPanel.Colors[i], GridPanel.TextColors[i], GridPanel.ColorNames[i]);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem10ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem10ActionPerformed
        System.out.println("Starting a new game");
        G.Moves = 0;
        G.MaxMoves = (int) Math.round(2.5 * GridPanel.GridSizeVS);
        titL.setText(String.format("Moves: %d / %d", G.Moves, G.MaxMoves));
        G.GenerateRandomly(GridPanel.GridSizeVS);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem9ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem9ActionPerformed
        System.out.println("Starting a new game");
        G.Moves = 0;
        G.MaxMoves = (int) Math.round(1 * GridPanel.GridSizeVL);
        titL.setText(String.format("Moves: %d / %d", G.Moves, G.MaxMoves));
        G.GenerateRandomly(GridPanel.GridSizeVL);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
      {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
          {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
              {
                if ("Windows".equals(info.getName()))
                  {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                  }
              }
          }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
          {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
          }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
              {
                new FMain().setVisible(true);
              }
        });
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    protected static javax.swing.JLabel titL;
    // End of variables declaration//GEN-END:variables

}
